import os
import re

from ..rsdf_io.rsdf_writer import export_rsdf
from . import mesh_export, urdf_writer

_TEMPLATE_DIR = os.path.join(os.path.dirname(__file__), "templates")

_PACKAGE_NAME_INVALID = re.compile(r"[^a-z0-9_]")

_PACKAGE_XML_TEMPLATE = """<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="http://download.ros.org/schema/package_format3.xsd"?>
<package format="3">
  <name>{package_name}</name>
  <version>0.1.0</version>
  <description>ROS2 description package for {robot_name}, generated by the RSDF Surface Tool Blender extension.</description>
  <maintainer email="{maintainer_email}">{maintainer_name}</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher_gui</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
"""

_CMAKE_TEMPLATE = """cmake_minimum_required(VERSION 3.8)
project({package_name})

find_package(ament_cmake REQUIRED)

install(DIRECTORY {install_dirs}
  DESTINATION share/${{PROJECT_NAME}}
)

ament_package()
"""

_LAUNCH_TEMPLATE = """import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration, Command
from launch_ros.actions import Node


def generate_launch_description():
    pkg_share = get_package_share_directory("{package_name}")
    default_urdf = os.path.join(pkg_share, "urdf", "{robot_name}.urdf")
    default_rviz = os.path.join(pkg_share, "launch", "display.rviz")

    urdf_arg = DeclareLaunchArgument("urdf", default_value=default_urdf)
    robot_description = Command(["cat ", LaunchConfiguration("urdf")])

    return LaunchDescription(
        [
            urdf_arg,
            Node(
                package="robot_state_publisher",
                executable="robot_state_publisher",
                output="screen",
                parameters=[{{"robot_description": robot_description}}],
            ),
            Node(
                package="joint_state_publisher_gui",
                executable="joint_state_publisher_gui",
                output="screen",
            ),
            Node(
                package="rviz2",
                executable="rviz2",
                output="screen",
                arguments=["-d", default_rviz],
            ),
        ]
    )
"""


def sanitize_package_name(name):
    name = _PACKAGE_NAME_INVALID.sub("_", name.lower())
    if not name or not name[0].isalpha():
        name = f"pkg_{name}"
    return name


def write_package(
    context,
    directory,
    package_name,
    robot_name,
    link_nodes,
    surfaces,
    include_rsdf,
    maintainer_name,
    maintainer_email,
):
    package_dir = os.path.join(directory, package_name)
    urdf_dir = os.path.join(package_dir, "urdf")
    meshes_dir = os.path.join(package_dir, "meshes")
    launch_dir = os.path.join(package_dir, "launch")

    os.makedirs(urdf_dir, exist_ok=True)
    os.makedirs(meshes_dir, exist_ok=True)
    os.makedirs(launch_dir, exist_ok=True)

    install_dirs = ["urdf", "meshes", "launch"]

    mesh_export.export_meshes(context, link_nodes, meshes_dir)

    urdf_str = urdf_writer.build_urdf_string(robot_name, package_name, link_nodes)
    with open(os.path.join(urdf_dir, f"{robot_name}.urdf"), "w") as f:
        f.write(urdf_str)

    if include_rsdf and len(surfaces) > 0:
        rsdf_dir = os.path.join(package_dir, "rsdf")
        os.makedirs(rsdf_dir, exist_ok=True)
        export_rsdf(os.path.join(rsdf_dir, f"{robot_name}.rsdf"), surfaces)
        install_dirs.append("rsdf")

    with open(os.path.join(package_dir, "package.xml"), "w") as f:
        f.write(
            _PACKAGE_XML_TEMPLATE.format(
                package_name=package_name,
                robot_name=robot_name,
                maintainer_name=maintainer_name,
                maintainer_email=maintainer_email,
            )
        )

    with open(os.path.join(package_dir, "CMakeLists.txt"), "w") as f:
        f.write(
            _CMAKE_TEMPLATE.format(
                package_name=package_name,
                install_dirs=" ".join(install_dirs),
            )
        )

    with open(os.path.join(launch_dir, "display.launch.py"), "w") as f:
        f.write(
            _LAUNCH_TEMPLATE.format(package_name=package_name, robot_name=robot_name)
        )

    with open(os.path.join(_TEMPLATE_DIR, "display.rviz")) as f:
        rviz_content = f.read()
    with open(os.path.join(launch_dir, "display.rviz"), "w") as f:
        f.write(rviz_content)

    return package_dir
